language: generic
sudo: required
os: linux

services:
  - docker

notifications:
  email:
    - "info@valentineus.link"

before_deploy:
  - sudo /bin/sh build.sh

after_deploy:
  - docker login --username "$DOCKER_USER" --password "$DOCKER_PASSWORD"
  - docker build --tag valentineus/mednafen-server ./
  - docker push valentineus/mednafen-server

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: "mednafen-server_*"
    email: "info@valentineus.link"
    api_key: $GITHUB_PROJECT_TOKEN
    on:
      tags: true